name: composeconfigstudio
services:
  composeconfigstudio:
    image: ghcr.io/nooblk-98/composeconfigstudio:latest
    container_name: composeconfigstudio
    ports:
      - "17400:3000"
    restart: unless-stopped
    networks:
      - composeconfigstudio

networks:
  composeconfigstudio:
    driver: bridge